### ISSUE TITLE
Preservation of application state between invocations of the system

### ISSUE THREAD

**Issue by RichardBruskiewich** [galaxy-genome-annotation/dockerized-gmod-deployment#16]
I am wondering if I'm doing something wrong, but each invocation of the **dockerized-gmod-deployment** (DGD) project build seems to completely overwrite user session changes to the state of the system, state items such as user accounts, Tripal customization, etc.

I am going to take a close look at the construction of the system to see whether we can build in two build/run modes: "Initialise" and "Reboot", the latter mode preserving the user data and core (external) configuration from the previous startup phase. If I get something working, I'll submit pull requests for review and consideration.

I suspect that some of the changes needed may need to be applied to the Docker builds of component images which form part of the aggregate system, components such as [docker-tripal](https://github.com/galaxy-genome-annotation/docker-tripal). There may be affiliated issues (and pull requests) posted to those component projects. Other changes may simply involve changes local to the DGD.  

This behaviour of the DGD may also be related to the apparent fragility of the system to selective restart of containers.

**Comment by hexylena** [comment]
Hi @RichardBruskiewich 

No changes should be needed to components or to this to add different "modes", it is simply a matter of mounting the correct volumes in the correct places (which is undocumented, sorry.)

I'll push to the master branch with these changes :)

**Comment by hexylena** [comment]
Maybe https://github.com/galaxy-genome-annotation/dockerized-gmod-deployment/commit/f25b5e088ff7be11029003b5df0f7caf233dae98 will help/

**Comment by abretaud** [comment]
Hum, so closing this one as it seems to be mostly a problem with tripal in https://github.com/galaxy-genome-annotation/docker-tripal/issues/34
Feel free to reopen or to open new issues on other docker images repos if you see this problem in something else than tripal

**Comment by RichardBruskiewich** [comment]
Yes, it is a docker-tripal specific problem.  As far as I can tell, the Tripal error: 

             ...tripal_1 exited with code 1

This appears to happen as soon as soon as I make a simple web dashboard level setting change to the Tripal configuration, for example, simply renaming the 'admin' account, resetting the default password and changing email address.  Then, tripal cannot seem to complete its initialization in a docker-compose down/up restart.  Deleting the tripal_db seems to allow it to restart, but then, the settings are lost.

That said, we can try to fix this in the context of docker-tripal.
