### ISSUE TITLE
Auth with galaxy/apollo/ldap

### ISSUE THREAD

**Issue by abretaud** [galaxy-genome-annotation/dockerized-gmod-deployment#6]
I'm feeling a little lost in the way to handle authentication on my setup, so maybe you can help me a little @erasche @nathandunn ?

So here's the situation:
- I have a docker-compose with these dockers:
  - ldap server with users already registered
  - nginx proxy configured to use the ldap server and populate the REMOTE_USER variable
  - an apollo server 2.0.5 with both authentication activated (first remote_user, then username/pass)
  - a galaxy server with apollo tools (with a few changes that will end up in a PR soon), not using the remote_user auth (but it could)

Now if I go directly to the apollo url, I get connected with ldap with no problem, but of course, no organism is available

I can use the galaxy tools to:
- register an account
- list organisms
- create an organism
- didn't tested much the other tools yet...

Now 2 questions:
- I'm not sure if registering an account is needed if I use remote_user both on galaxy and apollo? In fact I don't fully understand how the accounts are matched between galaxy and apollo
- how permissions are handled when someone connects to apollo using remote_user? In my case if users can connect, they should have permissions to annotate any genome available

(I also have some proxying problems, but I'll fix that later)

**Comment by hexylena** [comment]
- If you use remote_user on both, no, not needed. The accounts are matched based on email address. The tools use the galaxy user's email address when granting permissions in apollo.
- permissions are currently:
  - if you create an org in apollo via galaxy, you have access to that organism.
  - there is no way to share with other users in your instance
  - apollo admin users have access to everything (of course)

**Comment by hexylena** [comment]
I am, likewise, trying to figure out the auth story for us.

We use REMOTE_USER but with JASIG CAS from my university. Non-CAS users get username/password galaxy logins.

We're deploying N satellite services that all talk together to some degree, and the auth is going to be a huge issue. Will try and record more notes when I have them.

**Comment by abretaud** [comment]
Thank for the help! Yes, everything always gets complicated with auth... I'm interested by CAS too, we use ldap here, but that could change someday

> there is no way to share with other users in your instance

Ok, I'll need to look into this :/ I was planning to plug both apollo and galaxy on the ldap, but only a subset of users (admins) being allowed to access galaxy (just filtering based on ldap group). So admins would go to galaxy, prepare a good looking jbrowse and just deploy it as a new organism in apollo (or update it). And this organism would be accessible by any user going to the apollo server.

**Comment by hexylena** [comment]
Yeah, we used to use LDAP. It needed some more maintenance than what I could devote so switched to "university approved" one and people were happier.

As for sharing by default, hmm. You could maybe adjust your create_or_update script to share with a specific group by default, and then make sure everyone is in that group?

Interesting approach @ admins prepping instances and then pushing. Hadn't considered that style when I originally wrote create_or_update.

**Comment by nathandunn** [comment]
@erasche  / @abretaud  You should be able to emulate the code in [REMOTE_USER](https://github.com/GMOD/Apollo/blob/master/grails-app/services/org/bbop/apollo/authenticator/RemoteUserAuthenticatorService.groovy) auth (using external authentication, but creating internal users) for CAS, LDAP, Oauth, etc.  

Let me know how this goes.  Very curious.  I know that @childers did something with this by using web-services to directly inject users from their upper-level CAS system, but not sure if that would work in your situation.

**Comment by abretaud** [comment]
Things are beginning to work now on my side, with https://github.com/GMOD/Apollo/pull/1445 + some changes to galaxy-apollo tools (not yet online), I can now do what you suggested @erasche: I assign every new user to a default "annotators" group, and give permission to this group when creating new org.

For auth, the funny thing is that our users log in with a login like "abretaud" instead of an email, so I had to tweak the nginx config a little to have something that looks like an email...

**Comment by nathandunn** [comment]
@abretaud  You shouldn't have to use an email.   Another user had requested the use of just a regular string (though I think email can be a nice primary key).   

Let me know if its enforcing an email anywhere (other than on the initial registration page https://github.com/GMOD/Apollo/issues/1444) and I will fix it.

**Comment by abretaud** [comment]
Yes, I did my first tests with just the login and it worked well, but galaxy needs an email, and this email is used by the galaxy-apollo tools

**Comment by nathandunn** [comment]
Ahh, I see. It will work fine either way.

**Comment by nathandunn** [comment]
for Galaxy-apollo
